# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

all:
  javascripts:    [jquery-ui-1.8.13.custom.min.js, jquery.ui.datepicker-es.js, pago.js]
  stylesheets:    [redmond/jquery-ui-1.8.13.custom.css]

newSuccess:
#  stylesheets:    [main.css, stylesnew.css]
  has_layout:     true
  layout:         poplayout
  
editSuccess:
#  stylesheets:    [main.css, stylesnew.css]
  has_layout:     true
  layout:         poplayout

cerrarpopupSuccess:
  has_layout:     true
  layout:         poplayoutcerrar

comentarioSuccess:
  layout:         poplayout
actualizarpagosSuccess:
  layout:         layout_blank
  javascripts:    [-*,jquery-1.5.1.min.js]
  stylesheets:    [-*]