<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EstadoFactura', 'artelamp_1');

/**
 * BaseEstadoFactura
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_estadofactura
 * @property string $nombre_estadofactura
 * @property string $descripcion_estadofactura
 * @property Doctrine_Collection $Factura
 * 
 * @method integer             getIdEstadofactura()           Returns the current record's "id_estadofactura" value
 * @method string              getNombreEstadofactura()       Returns the current record's "nombre_estadofactura" value
 * @method string              getDescripcionEstadofactura()  Returns the current record's "descripcion_estadofactura" value
 * @method Doctrine_Collection getFactura()                   Returns the current record's "Factura" collection
 * @method EstadoFactura       setIdEstadofactura()           Sets the current record's "id_estadofactura" value
 * @method EstadoFactura       setNombreEstadofactura()       Sets the current record's "nombre_estadofactura" value
 * @method EstadoFactura       setDescripcionEstadofactura()  Sets the current record's "descripcion_estadofactura" value
 * @method EstadoFactura       setFactura()                   Sets the current record's "Factura" collection
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstadoFactura extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado_factura');
        $this->hasColumn('id_estadofactura', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_estadofactura', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('descripcion_estadofactura', 'string', 512, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 512,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Factura', array(
             'local' => 'id_estadofactura',
             'foreign' => 'id_estadofactura'));
    }
}