<?php

/**
 * BaseEstadoNotaDebito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_estado_nota_debito
 * @property string $nombre_estado_nota_debito
 * @property string $descripcion_estado_nota_debito
 * @property Doctrine_Collection $NotaDebito
 * 
 * @method integer             getIdEstadoNotaDebito()             Returns the current record's "id_estado_nota_debito" value
 * @method string              getNombreEstadoNotaDebito()         Returns the current record's "nombre_estado_nota_debito" value
 * @method string              getDescripcionEstadoNotaDebito()    Returns the current record's "descripcion_estado_nota_debito" value
 * @method Doctrine_Collection getNotaDebito()                     Returns the current record's "NotaDebito" collection
 * @method EstadoNotaDebito    setIdEstadoNotaDebito()             Sets the current record's "id_estado_nota_debito" value
 * @method EstadoNotaDebito    setNombreEstadoNotaDebito()         Sets the current record's "nombre_estado_nota_debito" value
 * @method EstadoNotaDebito    setDescripcionEstadoNotaDebito()    Sets the current record's "descripcion_estado_nota_debito" value
 * @method EstadoNotaDebito    setNotaDebito()                     Sets the current record's "NotaDebito" collection
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstadoNotaDebito extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado_nota_debito');
        $this->hasColumn('id_estado_nota_debito', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_estado_nota_debito', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('descripcion_estado_nota_debito', 'string', 512, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 512,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('NotaDebito', array(
             'local' => 'id_estado_nota_debito',
             'foreign' => 'id_estado_nota_debito'));
    }
}