<?php
// Connection Component Binding
//Doctrine_Manager::getInstance()->bindComponent('NotaVenta', 'artelamp');

/**
 * BaseNotaVenta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_compra
 * @property integer $id_proveedor
 * @property integer $id_nota_compra
 * @property integer $id_comprador
 * @property timestamp $fecha_nota
 * 
 * @method integer   getIdCompra()       Returns the current record's "id_compra" value
 * @method integer   getIdProveedor()    Returns the current record's "id_proveedor" value
 * @method integer   getIdNotaCompra()   Returns the current record's "id_nota_compra" value
 * @method integer   getIdComprador()    Returns the current record's "id_comprador" value
 * @method timestamp getFechaNota()      Returns the current record's "fecha_nota" value
 * @method NotaVenta setIdCompra()       Sets the current record's "id_compra" value
 * @method NotaVenta setIdProveedor()    Sets the current record's "id_proveedor" value
 * @method NotaVenta setIdNotaCompra()   Sets the current record's "id_nota_compra" value
 * @method NotaVenta setIdComprador()    Sets the current record's "id_comprador" value
 * @method NotaVenta setFechaNota()      Sets the current record's "fecha_nota" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseNotaVenta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nota_venta');
        $this->hasColumn('id_compra', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_proveedor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_nota_compra', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_comprador', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_nota', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}