<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Proveedor', 'artelamp_1');

/**
 * BaseProveedor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_proveedor
 * @property string $nombre_proveedor
 * @property string $giro_proveedor
 * @property Doctrine_Collection $OrdenReposicion
 * 
 * @method integer             getIdProveedor()      Returns the current record's "id_proveedor" value
 * @method string              getNombreProveedor()  Returns the current record's "nombre_proveedor" value
 * @method string              getGiroProveedor()    Returns the current record's "giro_proveedor" value
 * @method Doctrine_Collection getOrdenReposicion()  Returns the current record's "OrdenReposicion" collection
 * @method Proveedor           setIdProveedor()      Sets the current record's "id_proveedor" value
 * @method Proveedor           setNombreProveedor()  Sets the current record's "nombre_proveedor" value
 * @method Proveedor           setGiroProveedor()    Sets the current record's "giro_proveedor" value
 * @method Proveedor           setOrdenReposicion()  Sets the current record's "OrdenReposicion" collection
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseProveedor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('proveedor');
        $this->hasColumn('id_proveedor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_proveedor', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('giro_proveedor', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('OrdenReposicion', array(
             'local' => 'id_proveedor',
             'foreign' => 'id_proveedor'));
    }
}