<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Divisiones', 'artelamp');

/**
 * BaseDivisiones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_division
 * @property string $descripcion_division
 * 
 * @method integer    getIdDivision()           Returns the current record's "id_division" value
 * @method string     getDescripcionDivision()  Returns the current record's "descripcion_division" value
 * @method Divisiones setIdDivision()           Sets the current record's "id_division" value
 * @method Divisiones setDescripcionDivision()  Sets the current record's "descripcion_division" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDivisiones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('divisiones');
        $this->hasColumn('id_division', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('descripcion_division', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}