<?php
// Connection Component Binding
//Doctrine_Manager::getInstance()->bindComponent('NotacreditoFactura', 'artelamp_1');

/**
 * BaseNotacreditoFactura
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_factura
 * @property integer $id_nota_credito
 * @property NotaCredito $NotaCredito
 * @property Factura $Factura
 * 
 * @method integer            getIdFactura()       Returns the current record's "id_factura" value
 * @method integer            getIdNotaCredito()   Returns the current record's "id_nota_credito" value
 * @method NotaCredito        getNotaCredito()     Returns the current record's "NotaCredito" value
 * @method Factura            getFactura()         Returns the current record's "Factura" value
 * @method NotacreditoFactura setIdFactura()       Sets the current record's "id_factura" value
 * @method NotacreditoFactura setIdNotaCredito()   Sets the current record's "id_nota_credito" value
 * @method NotacreditoFactura setNotaCredito()     Sets the current record's "NotaCredito" value
 * @method NotacreditoFactura setFactura()         Sets the current record's "Factura" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotacreditoFactura extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notacredito_factura');
        $this->hasColumn('id_factura', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_nota_credito', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NotaCredito', array(
             'local' => 'id_nota_credito',
             'foreign' => 'id_nota_credito'));

        $this->hasOne('Factura', array(
             'local' => 'id_factura',
             'foreign' => 'id_factura'));
    }
}