<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SalidaActivo', 'artelamp');

/**
 * BaseSalidaActivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_salida_ac
 * @property string $id_salida
 * @property string $id_prod
 * @property integer $cantidad
 * @property integer $precio
 * @property float $descuento
 * @property string $estado
 * @property integer $parcializado_de
 * @property integer $requiere_permiso
 * @property timestamp $fecha_sal_act
 * @property integer $nacional
 * @property integer $faltan
 * @property integer $comp_editada
 * @property timestamp $fecha_modif
 * @property string $comentario_bodega
 * @property integer $id_factura
 * @property integer $factura
 * @property integer $id_guia
 * @property integer $guia
 * @property integer $id_boleta
 * @property integer $boleta
 * @property string $despacho
 * @property integer $facturado
 * 
 * @method integer      getIdSalidaAc()        Returns the current record's "id_salida_ac" value
 * @method string       getIdSalida()          Returns the current record's "id_salida" value
 * @method string       getIdProd()            Returns the current record's "id_prod" value
 * @method integer      getCantidad()          Returns the current record's "cantidad" value
 * @method integer      getPrecio()            Returns the current record's "precio" value
 * @method float        getDescuento()         Returns the current record's "descuento" value
 * @method string       getEstado()            Returns the current record's "estado" value
 * @method integer      getParcializadoDe()    Returns the current record's "parcializado_de" value
 * @method integer      getRequierePermiso()   Returns the current record's "requiere_permiso" value
 * @method timestamp    getFechaSalAct()       Returns the current record's "fecha_sal_act" value
 * @method integer      getNacional()          Returns the current record's "nacional" value
 * @method integer      getFaltan()            Returns the current record's "faltan" value
 * @method integer      getCompEditada()       Returns the current record's "comp_editada" value
 * @method timestamp    getFechaModif()        Returns the current record's "fecha_modif" value
 * @method string       getComentarioBodega()  Returns the current record's "comentario_bodega" value
 * @method integer      getIdFactura()         Returns the current record's "id_factura" value
 * @method integer      getFactura()           Returns the current record's "factura" value
 * @method integer      getIdGuia()            Returns the current record's "id_guia" value
 * @method integer      getGuia()              Returns the current record's "guia" value
 * @method integer      getIdBoleta()          Returns the current record's "id_boleta" value
 * @method integer      getBoleta()            Returns the current record's "boleta" value
 * @method string       getDespacho()          Returns the current record's "despacho" value
 * @method integer      getFacturado()         Returns the current record's "facturado" value
 * @method SalidaActivo setIdSalidaAc()        Sets the current record's "id_salida_ac" value
 * @method SalidaActivo setIdSalida()          Sets the current record's "id_salida" value
 * @method SalidaActivo setIdProd()            Sets the current record's "id_prod" value
 * @method SalidaActivo setCantidad()          Sets the current record's "cantidad" value
 * @method SalidaActivo setPrecio()            Sets the current record's "precio" value
 * @method SalidaActivo setDescuento()         Sets the current record's "descuento" value
 * @method SalidaActivo setEstado()            Sets the current record's "estado" value
 * @method SalidaActivo setParcializadoDe()    Sets the current record's "parcializado_de" value
 * @method SalidaActivo setRequierePermiso()   Sets the current record's "requiere_permiso" value
 * @method SalidaActivo setFechaSalAct()       Sets the current record's "fecha_sal_act" value
 * @method SalidaActivo setNacional()          Sets the current record's "nacional" value
 * @method SalidaActivo setFaltan()            Sets the current record's "faltan" value
 * @method SalidaActivo setCompEditada()       Sets the current record's "comp_editada" value
 * @method SalidaActivo setFechaModif()        Sets the current record's "fecha_modif" value
 * @method SalidaActivo setComentarioBodega()  Sets the current record's "comentario_bodega" value
 * @method SalidaActivo setIdFactura()         Sets the current record's "id_factura" value
 * @method SalidaActivo setFactura()           Sets the current record's "factura" value
 * @method SalidaActivo setIdGuia()            Sets the current record's "id_guia" value
 * @method SalidaActivo setGuia()              Sets the current record's "guia" value
 * @method SalidaActivo setIdBoleta()          Sets the current record's "id_boleta" value
 * @method SalidaActivo setBoleta()            Sets the current record's "boleta" value
 * @method SalidaActivo setDespacho()          Sets the current record's "despacho" value
 * @method SalidaActivo setFacturado()         Sets the current record's "facturado" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSalidaActivo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('salida_activo');
        $this->hasColumn('id_salida_ac', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_salida', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('id_prod', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('cantidad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('precio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('descuento', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('estado', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '11',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('parcializado_de', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('requiere_permiso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_sal_act', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('nacional', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('faltan', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('comp_editada', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_modif', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('comentario_bodega', 'string', 1000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1000,
             ));
        $this->hasColumn('id_factura', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('factura', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_guia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('guia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_boleta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('boleta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('despacho', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'N',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('facturado', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}