<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Pasillo', 'artelamp');

/**
 * BasePasillo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_pasillo
 * @property integer $id_nivel
 * @property string $codigo_pasillo
 * @property string $descripcion_pasillo
 * @property Nivel $Nivel
 * @property Doctrine_Collection $Espacio
 * 
 * @method integer             getIdPasillo()           Returns the current record's "id_pasillo" value
 * @method integer             getIdNivel()             Returns the current record's "id_nivel" value
 * @method string              getCodigoPasillo()       Returns the current record's "codigo_pasillo" value
 * @method string              getDescripcionPasillo()  Returns the current record's "descripcion_pasillo" value
 * @method Nivel               getNivel()               Returns the current record's "Nivel" value
 * @method Doctrine_Collection getEspacio()             Returns the current record's "Espacio" collection
 * @method Pasillo             setIdPasillo()           Sets the current record's "id_pasillo" value
 * @method Pasillo             setIdNivel()             Sets the current record's "id_nivel" value
 * @method Pasillo             setCodigoPasillo()       Sets the current record's "codigo_pasillo" value
 * @method Pasillo             setDescripcionPasillo()  Sets the current record's "descripcion_pasillo" value
 * @method Pasillo             setNivel()               Sets the current record's "Nivel" value
 * @method Pasillo             setEspacio()             Sets the current record's "Espacio" collection
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BasePasillo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pasillo');
        $this->hasColumn('id_pasillo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_nivel', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo_pasillo', 'string', 15, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('descripcion_pasillo', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Nivel', array(
             'local' => 'id_nivel',
             'foreign' => 'id_nivel'));

        $this->hasMany('Espacio', array(
             'local' => 'id_pasillo',
             'foreign' => 'id_pasillo'));
    }
}