<?php

/**
 * BaseDivision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_division
 * @property string $nombre_division
 * @property string $descripcion_division
 * @property Doctrine_Collection $Factura
 * 
 * @method integer             getIdDivision()           Returns the current record's "id_division" value
 * @method string              getNombreDivision()       Returns the current record's "nombre_division" value
 * @method string              getDescripcionDivision()  Returns the current record's "descripcion_division" value
 * @method Doctrine_Collection getFactura()              Returns the current record's "Factura" collection
 * @method Division            setIdDivision()           Sets the current record's "id_division" value
 * @method Division            setNombreDivision()       Sets the current record's "nombre_division" value
 * @method Division            setDescripcionDivision()  Sets the current record's "descripcion_division" value
 * @method Division            setFactura()              Sets the current record's "Factura" collection
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDivision extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('division');
        $this->hasColumn('id_division', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_division', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('descripcion_division', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 64,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Factura', array(
             'local' => 'id_division',
             'foreign' => 'id_division'));
    }
}