<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Nivel', 'artelamp');

/**
 * BaseNivel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_nivel
 * @property string $nombre_nivel
 * @property integer $numero_nivel
 * @property Doctrine_Collection $Pasillo
 * 
 * @method integer             getIdNivel()      Returns the current record's "id_nivel" value
 * @method string              getNombreNivel()  Returns the current record's "nombre_nivel" value
 * @method integer             getNumeroNivel()  Returns the current record's "numero_nivel" value
 * @method Doctrine_Collection getPasillo()      Returns the current record's "Pasillo" collection
 * @method Nivel               setIdNivel()      Sets the current record's "id_nivel" value
 * @method Nivel               setNombreNivel()  Sets the current record's "nombre_nivel" value
 * @method Nivel               setNumeroNivel()  Sets the current record's "numero_nivel" value
 * @method Nivel               setPasillo()      Sets the current record's "Pasillo" collection
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseNivel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nivel');
        $this->hasColumn('id_nivel', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_nivel', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('numero_nivel', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Pasillo', array(
             'local' => 'id_nivel',
             'foreign' => 'id_nivel'));
    }
}