<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CotizacionesEstado', 'artelamp');

/**
 * BaseCotizacionesEstado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property integer $visto_por_vendedor
 * 
 * @method integer            getId()                 Returns the current record's "id" value
 * @method string             getDescripcion()        Returns the current record's "descripcion" value
 * @method integer            getVistoPorVendedor()   Returns the current record's "visto_por_vendedor" value
 * @method CotizacionesEstado setId()                 Sets the current record's "id" value
 * @method CotizacionesEstado setDescripcion()        Sets the current record's "descripcion" value
 * @method CotizacionesEstado setVistoPorVendedor()   Sets the current record's "visto_por_vendedor" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseCotizacionesEstado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cotizaciones_estado');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('visto_por_vendedor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}