<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Despacho', 'artelamp');

/**
 * BaseDespacho
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_despacho
 * @property integer $id_chofer
 * @property integer $id_vehiculo
 * @property timestamp $fecha_estimada
 * @property integer $estado
 * @property string $comentario
 * @property timestamp $fecha_creacion
 * @property integer $bultos
 * 
 * @method integer   getIdDespacho()     Returns the current record's "id_despacho" value
 * @method integer   getIdChofer()       Returns the current record's "id_chofer" value
 * @method integer   getIdVehiculo()     Returns the current record's "id_vehiculo" value
 * @method timestamp getFechaEstimada()  Returns the current record's "fecha_estimada" value
 * @method integer   getEstado()         Returns the current record's "estado" value
 * @method string    getComentario()     Returns the current record's "comentario" value
 * @method timestamp getFechaCreacion()  Returns the current record's "fecha_creacion" value
 * @method integer   getBultos()         Returns the current record's "bultos" value
 * @method Despacho  setIdDespacho()     Sets the current record's "id_despacho" value
 * @method Despacho  setIdChofer()       Sets the current record's "id_chofer" value
 * @method Despacho  setIdVehiculo()     Sets the current record's "id_vehiculo" value
 * @method Despacho  setFechaEstimada()  Sets the current record's "fecha_estimada" value
 * @method Despacho  setEstado()         Sets the current record's "estado" value
 * @method Despacho  setComentario()     Sets the current record's "comentario" value
 * @method Despacho  setFechaCreacion()  Sets the current record's "fecha_creacion" value
 * @method Despacho  setBultos()         Sets the current record's "bultos" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseDespacho extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('despacho');
        $this->hasColumn('id_despacho', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_chofer', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_vehiculo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_estimada', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('estado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('comentario', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('fecha_creacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('bultos', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}