<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FormasPago', 'artelamp');

/**
 * BaseFormasPago
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_pago
 * @property string $descripcion_pago
 * @property integer $vencimiento
 * 
 * @method integer    getIdPago()           Returns the current record's "id_pago" value
 * @method string     getDescripcionPago()  Returns the current record's "descripcion_pago" value
 * @method integer    getVencimiento()      Returns the current record's "vencimiento" value
 * @method FormasPago setIdPago()           Sets the current record's "id_pago" value
 * @method FormasPago setDescripcionPago()  Sets the current record's "descripcion_pago" value
 * @method FormasPago setVencimiento()      Sets the current record's "vencimiento" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseFormasPago extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('formas_pago');
        $this->hasColumn('id_pago', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('descripcion_pago', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('vencimiento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}