<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Salida', 'artelamp');

/**
 * BaseSalida
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_salida
 * @property string $id_cliente
 * @property string $id_responsable
 * @property string $id_responsable2
 * @property integer $porcentaje
 * @property integer $id_division
 * @property string $id_sucursal
 * @property date $fecha
 * @property timestamp $fecha_ingreso
 * @property string $comentario
 * @property integer $estado
 * @property timestamp $fecha_salida
 * @property string $orden_compra
 * @property string $observacion
 * @property string $url_orden_compra
 * @property integer $condicion_pago
 * @property integer $neto
 * @property integer $es_muestra
 * @property float $descuento_salida
 * @property string $ingresado_por
 * @property date $fecha_sugerida
 * @property integer $anulador
 * @property integer $id_empresa
 * @property string $comentario_finanzas
 * @property string $comentario_bodega
 * @property string $transporte
 * @property timestamp $fecha_comercial
 * @property timestamp $fecha_finanzas
 * @property integer $neto_aprobado
 * 
 * @method integer   getIdSalida()            Returns the current record's "id_salida" value
 * @method string    getIdCliente()           Returns the current record's "id_cliente" value
 * @method string    getIdResponsable()       Returns the current record's "id_responsable" value
 * @method string    getIdResponsable2()      Returns the current record's "id_responsable2" value
 * @method integer   getPorcentaje()          Returns the current record's "porcentaje" value
 * @method integer   getIdDivision()          Returns the current record's "id_division" value
 * @method string    getIdSucursal()          Returns the current record's "id_sucursal" value
 * @method date      getFecha()               Returns the current record's "fecha" value
 * @method timestamp getFechaIngreso()        Returns the current record's "fecha_ingreso" value
 * @method string    getComentario()          Returns the current record's "comentario" value
 * @method integer   getEstado()              Returns the current record's "estado" value
 * @method timestamp getFechaSalida()         Returns the current record's "fecha_salida" value
 * @method string    getOrdenCompra()         Returns the current record's "orden_compra" value
 * @method string    getObservacion()         Returns the current record's "observacion" value
 * @method string    getUrlOrdenCompra()      Returns the current record's "url_orden_compra" value
 * @method integer   getCondicionPago()       Returns the current record's "condicion_pago" value
 * @method integer   getNeto()                Returns the current record's "neto" value
 * @method integer   getEsMuestra()           Returns the current record's "es_muestra" value
 * @method float     getDescuentoSalida()     Returns the current record's "descuento_salida" value
 * @method string    getIngresadoPor()        Returns the current record's "ingresado_por" value
 * @method date      getFechaSugerida()       Returns the current record's "fecha_sugerida" value
 * @method integer   getAnulador()            Returns the current record's "anulador" value
 * @method integer   getIdEmpresa()           Returns the current record's "id_empresa" value
 * @method string    getComentarioFinanzas()  Returns the current record's "comentario_finanzas" value
 * @method string    getComentarioBodega()    Returns the current record's "comentario_bodega" value
 * @method string    getTransporte()          Returns the current record's "transporte" value
 * @method timestamp getFechaComercial()      Returns the current record's "fecha_comercial" value
 * @method timestamp getFechaFinanzas()       Returns the current record's "fecha_finanzas" value
 * @method integer   getNetoAprobado()        Returns the current record's "neto_aprobado" value
 * @method Salida    setIdSalida()            Sets the current record's "id_salida" value
 * @method Salida    setIdCliente()           Sets the current record's "id_cliente" value
 * @method Salida    setIdResponsable()       Sets the current record's "id_responsable" value
 * @method Salida    setIdResponsable2()      Sets the current record's "id_responsable2" value
 * @method Salida    setPorcentaje()          Sets the current record's "porcentaje" value
 * @method Salida    setIdDivision()          Sets the current record's "id_division" value
 * @method Salida    setIdSucursal()          Sets the current record's "id_sucursal" value
 * @method Salida    setFecha()               Sets the current record's "fecha" value
 * @method Salida    setFechaIngreso()        Sets the current record's "fecha_ingreso" value
 * @method Salida    setComentario()          Sets the current record's "comentario" value
 * @method Salida    setEstado()              Sets the current record's "estado" value
 * @method Salida    setFechaSalida()         Sets the current record's "fecha_salida" value
 * @method Salida    setOrdenCompra()         Sets the current record's "orden_compra" value
 * @method Salida    setObservacion()         Sets the current record's "observacion" value
 * @method Salida    setUrlOrdenCompra()      Sets the current record's "url_orden_compra" value
 * @method Salida    setCondicionPago()       Sets the current record's "condicion_pago" value
 * @method Salida    setNeto()                Sets the current record's "neto" value
 * @method Salida    setEsMuestra()           Sets the current record's "es_muestra" value
 * @method Salida    setDescuentoSalida()     Sets the current record's "descuento_salida" value
 * @method Salida    setIngresadoPor()        Sets the current record's "ingresado_por" value
 * @method Salida    setFechaSugerida()       Sets the current record's "fecha_sugerida" value
 * @method Salida    setAnulador()            Sets the current record's "anulador" value
 * @method Salida    setIdEmpresa()           Sets the current record's "id_empresa" value
 * @method Salida    setComentarioFinanzas()  Sets the current record's "comentario_finanzas" value
 * @method Salida    setComentarioBodega()    Sets the current record's "comentario_bodega" value
 * @method Salida    setTransporte()          Sets the current record's "transporte" value
 * @method Salida    setFechaComercial()      Sets the current record's "fecha_comercial" value
 * @method Salida    setFechaFinanzas()       Sets the current record's "fecha_finanzas" value
 * @method Salida    setNetoAprobado()        Sets the current record's "neto_aprobado" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSalida extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('salida');
        $this->hasColumn('id_salida', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_cliente', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('id_responsable', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('id_responsable2', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('porcentaje', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_division', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_sucursal', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_ingreso', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('comentario', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('estado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_salida', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('orden_compra', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('observacion', 'string', 2555, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2555,
             ));
        $this->hasColumn('url_orden_compra', 'string', 2000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'NULL',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2000,
             ));
        $this->hasColumn('condicion_pago', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('neto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('es_muestra', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('descuento_salida', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ingresado_por', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('fecha_sugerida', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('anulador', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_empresa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('comentario_finanzas', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('comentario_bodega', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('transporte', 'string', 2000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2000,
             ));
        $this->hasColumn('fecha_comercial', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_finanzas', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('neto_aprobado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}