<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('InfoContactos', 'artelamp');

/**
 * BaseInfoContactos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_persona
 * @property string $nombre_completo
 * @property string $apellido
 * @property string $rut
 * @property string $correo
 * @property string $celular
 * @property string $fono_casa
 * @property date $fecha_nacimiento
 * @property integer $id_vendedor
 * 
 * @method integer       getIdPersona()        Returns the current record's "id_persona" value
 * @method string        getNombreCompleto()   Returns the current record's "nombre_completo" value
 * @method string        getApellido()         Returns the current record's "apellido" value
 * @method string        getRut()              Returns the current record's "rut" value
 * @method string        getCorreo()           Returns the current record's "correo" value
 * @method string        getCelular()          Returns the current record's "celular" value
 * @method string        getFonoCasa()         Returns the current record's "fono_casa" value
 * @method date          getFechaNacimiento()  Returns the current record's "fecha_nacimiento" value
 * @method integer       getIdVendedor()       Returns the current record's "id_vendedor" value
 * @method InfoContactos setIdPersona()        Sets the current record's "id_persona" value
 * @method InfoContactos setNombreCompleto()   Sets the current record's "nombre_completo" value
 * @method InfoContactos setApellido()         Sets the current record's "apellido" value
 * @method InfoContactos setRut()              Sets the current record's "rut" value
 * @method InfoContactos setCorreo()           Sets the current record's "correo" value
 * @method InfoContactos setCelular()          Sets the current record's "celular" value
 * @method InfoContactos setFonoCasa()         Sets the current record's "fono_casa" value
 * @method InfoContactos setFechaNacimiento()  Sets the current record's "fecha_nacimiento" value
 * @method InfoContactos setIdVendedor()       Sets the current record's "id_vendedor" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInfoContactos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('info_contactos');
        $this->hasColumn('id_persona', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_completo', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('apellido', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('rut', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('correo', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('celular', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('fono_casa', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('fecha_nacimiento', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_vendedor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}