<?php
// Connection Component Binding
//Doctrine_Manager::getInstance()->bindComponent('EstadoCuota', 'artelamp_1');

/**
 * BaseEstadoCuota
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_estado_cuota
 * @property string $nombre_estado_cuota
 * @property string $descripcion_estado_cuota
 * @property Doctrine_Collection $Cuota
 * 
 * @method integer             getIdEstadoCuota()            Returns the current record's "id_estado_cuota" value
 * @method string              getNombreEstadoCuota()        Returns the current record's "nombre_estado_cuota" value
 * @method string              getDescripcionEstadoCuota()   Returns the current record's "descripcion_estado_cuota" value
 * @method Doctrine_Collection getCuota()                    Returns the current record's "Cuota" collection
 * @method EstadoCuota         setIdEstadoCuota()            Sets the current record's "id_estado_cuota" value
 * @method EstadoCuota         setNombreEstadoCuota()        Sets the current record's "nombre_estado_cuota" value
 * @method EstadoCuota         setDescripcionEstadoCuota()   Sets the current record's "descripcion_estado_cuota" value
 * @method EstadoCuota         setCuota()                    Sets the current record's "Cuota" collection
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseEstadoCuota extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado_cuota');
        $this->hasColumn('id_estado_cuota', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_estado_cuota', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('descripcion_estado_cuota', 'string', 300, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 300,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Cuota', array(
             'local' => 'id_estado_cuota',
             'foreign' => 'id_estado_cuota'));
    }
}