<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EstadoGuia', 'artelamp_1');

/**
 * BaseEstadoGuia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_estadoguia
 * @property string $nombre_estadoguia
 * @property string $descripcion_estadoguia
 * @property Doctrine_Collection $Guia
 * 
 * @method integer             getIdEstadoguia()           Returns the current record's "id_estadoguia" value
 * @method string              getNombreEstadoguia()       Returns the current record's "nombre_estadoguia" value
 * @method string              getDescripcionEstadoguia()  Returns the current record's "descripcion_estadoguia" value
 * @method Doctrine_Collection getGuia()                   Returns the current record's "Guia" collection
 * @method EstadoGuia          setIdEstadoguia()           Sets the current record's "id_estadoguia" value
 * @method EstadoGuia          setNombreEstadoguia()       Sets the current record's "nombre_estadoguia" value
 * @method EstadoGuia          setDescripcionEstadoguia()  Sets the current record's "descripcion_estadoguia" value
 * @method EstadoGuia          setGuia()                   Sets the current record's "Guia" collection
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstadoGuia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado_guia');
        $this->hasColumn('id_estadoguia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_estadoguia', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('descripcion_estadoguia', 'string', 512, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 512,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Guia', array(
             'local' => 'id_estadoguia',
             'foreign' => 'id_estadoguia'));
    }
}