<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cotizaciones', 'artelamp');

/**
 * BaseCotizaciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_cotizacion
 * @property string $rut_cliente
 * @property string $obra
 * @property string $contacto
 * @property string $rut_contacto
 * @property string $telefono_contacto
 * @property string $correo_contacto
 * @property timestamp $fecha_ingreso
 * @property timestamp $fecha_emision
 * @property date $fecha_estimada_cierre
 * @property string $validez
 * @property integer $total_neto
 * @property integer $descuento_a_total
 * @property integer $enviado
 * @property integer $id_vendedor
 * @property integer $id_empresa
 * @property integer $estado
 * @property string $comentario
 * @property string $comentario_ventas
 * @property string $comentario_vendedor
 * 
 * @method integer      getIdCotizacion()          Returns the current record's "id_cotizacion" value
 * @method string       getRutCliente()            Returns the current record's "rut_cliente" value
 * @method string       getObra()                  Returns the current record's "obra" value
 * @method string       getContacto()              Returns the current record's "contacto" value
 * @method string       getRutContacto()           Returns the current record's "rut_contacto" value
 * @method string       getTelefonoContacto()      Returns the current record's "telefono_contacto" value
 * @method string       getCorreoContacto()        Returns the current record's "correo_contacto" value
 * @method timestamp    getFechaIngreso()          Returns the current record's "fecha_ingreso" value
 * @method timestamp    getFechaEmision()          Returns the current record's "fecha_emision" value
 * @method date         getFechaEstimadaCierre()   Returns the current record's "fecha_estimada_cierre" value
 * @method string       getValidez()               Returns the current record's "validez" value
 * @method integer      getTotalNeto()             Returns the current record's "total_neto" value
 * @method integer      getDescuentoATotal()       Returns the current record's "descuento_a_total" value
 * @method integer      getEnviado()               Returns the current record's "enviado" value
 * @method integer      getIdVendedor()            Returns the current record's "id_vendedor" value
 * @method integer      getIdEmpresa()             Returns the current record's "id_empresa" value
 * @method integer      getEstado()                Returns the current record's "estado" value
 * @method string       getComentario()            Returns the current record's "comentario" value
 * @method string       getComentarioVentas()      Returns the current record's "comentario_ventas" value
 * @method string       getComentarioVendedor()    Returns the current record's "comentario_vendedor" value
 * @method Cotizaciones setIdCotizacion()          Sets the current record's "id_cotizacion" value
 * @method Cotizaciones setRutCliente()            Sets the current record's "rut_cliente" value
 * @method Cotizaciones setObra()                  Sets the current record's "obra" value
 * @method Cotizaciones setContacto()              Sets the current record's "contacto" value
 * @method Cotizaciones setRutContacto()           Sets the current record's "rut_contacto" value
 * @method Cotizaciones setTelefonoContacto()      Sets the current record's "telefono_contacto" value
 * @method Cotizaciones setCorreoContacto()        Sets the current record's "correo_contacto" value
 * @method Cotizaciones setFechaIngreso()          Sets the current record's "fecha_ingreso" value
 * @method Cotizaciones setFechaEmision()          Sets the current record's "fecha_emision" value
 * @method Cotizaciones setFechaEstimadaCierre()   Sets the current record's "fecha_estimada_cierre" value
 * @method Cotizaciones setValidez()               Sets the current record's "validez" value
 * @method Cotizaciones setTotalNeto()             Sets the current record's "total_neto" value
 * @method Cotizaciones setDescuentoATotal()       Sets the current record's "descuento_a_total" value
 * @method Cotizaciones setEnviado()               Sets the current record's "enviado" value
 * @method Cotizaciones setIdVendedor()            Sets the current record's "id_vendedor" value
 * @method Cotizaciones setIdEmpresa()             Sets the current record's "id_empresa" value
 * @method Cotizaciones setEstado()                Sets the current record's "estado" value
 * @method Cotizaciones setComentario()            Sets the current record's "comentario" value
 * @method Cotizaciones setComentarioVentas()      Sets the current record's "comentario_ventas" value
 * @method Cotizaciones setComentarioVendedor()    Sets the current record's "comentario_vendedor" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCotizaciones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cotizaciones');
        $this->hasColumn('id_cotizacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('rut_cliente', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('obra', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('contacto', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('rut_contacto', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('telefono_contacto', 'string', 12, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 12,
             ));
        $this->hasColumn('correo_contacto', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('fecha_ingreso', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_emision', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_estimada_cierre', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('validez', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('total_neto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('descuento_a_total', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('enviado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_vendedor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_empresa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('estado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('comentario', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('comentario_ventas', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('comentario_vendedor', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}