<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Costos', 'artelamp');

/**
 * BaseCostos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_costo
 * @property string $id_prod_costo
 * @property string $descripcion_costo
 * @property float $cost_imp
 * @property float $cost_nac
 * @property string $codigo_madre
 * 
 * @method integer getIdCosto()           Returns the current record's "id_costo" value
 * @method string  getIdProdCosto()       Returns the current record's "id_prod_costo" value
 * @method string  getDescripcionCosto()  Returns the current record's "descripcion_costo" value
 * @method float   getCostImp()           Returns the current record's "cost_imp" value
 * @method float   getCostNac()           Returns the current record's "cost_nac" value
 * @method string  getCodigoMadre()       Returns the current record's "codigo_madre" value
 * @method Costos  setIdCosto()           Sets the current record's "id_costo" value
 * @method Costos  setIdProdCosto()       Sets the current record's "id_prod_costo" value
 * @method Costos  setDescripcionCosto()  Sets the current record's "descripcion_costo" value
 * @method Costos  setCostImp()           Sets the current record's "cost_imp" value
 * @method Costos  setCostNac()           Sets the current record's "cost_nac" value
 * @method Costos  setCodigoMadre()       Sets the current record's "codigo_madre" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCostos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('costos');
        $this->hasColumn('id_costo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_prod_costo', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('descripcion_costo', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('cost_imp', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('cost_nac', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('codigo_madre', 'string', 2000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}