<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CotizacionesPiezas', 'artelamp');

/**
 * BaseCotizacionesPiezas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_cotizaciones_producto
 * @property string $id_pieza
 * @property integer $cantidad
 * @property integer $es_extra
 * @property integer $precio_pieza
 * @property string $nota_pieza
 * 
 * @method integer            getId()                       Returns the current record's "id" value
 * @method integer            getIdCotizacionesProducto()   Returns the current record's "id_cotizaciones_producto" value
 * @method string             getIdPieza()                  Returns the current record's "id_pieza" value
 * @method integer            getCantidad()                 Returns the current record's "cantidad" value
 * @method integer            getEsExtra()                  Returns the current record's "es_extra" value
 * @method integer            getPrecioPieza()              Returns the current record's "precio_pieza" value
 * @method string             getNotaPieza()                Returns the current record's "nota_pieza" value
 * @method CotizacionesPiezas setId()                       Sets the current record's "id" value
 * @method CotizacionesPiezas setIdCotizacionesProducto()   Sets the current record's "id_cotizaciones_producto" value
 * @method CotizacionesPiezas setIdPieza()                  Sets the current record's "id_pieza" value
 * @method CotizacionesPiezas setCantidad()                 Sets the current record's "cantidad" value
 * @method CotizacionesPiezas setEsExtra()                  Sets the current record's "es_extra" value
 * @method CotizacionesPiezas setPrecioPieza()              Sets the current record's "precio_pieza" value
 * @method CotizacionesPiezas setNotaPieza()                Sets the current record's "nota_pieza" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCotizacionesPiezas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cotizaciones_piezas');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_cotizaciones_producto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_pieza', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('cantidad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('es_extra', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('precio_pieza', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nota_pieza', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}