<?php

/**
 * BaseNotadebitoDetalle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_detalle_activo
 * @property integer $id_nota_debito
 * @property NotaDebito $NotaDebito
 * @property DetalleActivo $DetalleActivo
 * 
 * @method integer           getIdDetalleActivo()   Returns the current record's "id_detalle_activo" value
 * @method integer           getIdNotaDebito()      Returns the current record's "id_nota_debito" value
 * @method NotaDebito        getNotaDebito()        Returns the current record's "NotaDebito" value
 * @method DetalleActivo     getDetalleActivo()     Returns the current record's "DetalleActivo" value
 * @method NotadebitoDetalle setIdDetalleActivo()   Sets the current record's "id_detalle_activo" value
 * @method NotadebitoDetalle setIdNotaDebito()      Sets the current record's "id_nota_debito" value
 * @method NotadebitoDetalle setNotaDebito()        Sets the current record's "NotaDebito" value
 * @method NotadebitoDetalle setDetalleActivo()     Sets the current record's "DetalleActivo" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotadebitoDetalle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notadebito_detalle');
        $this->hasColumn('id_detalle_activo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_nota_debito', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NotaDebito', array(
             'local' => 'id_nota_debito',
             'foreign' => 'id_nota_debito'));

        $this->hasOne('DetalleActivo', array(
             'local' => 'id_detalle_activo',
             'foreign' => 'id_detalle_activo'));
    }
}