<?php

/**
 * BaseReferenciaDetalle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_detalle_activo1
 * @property integer $id_detalle_activo2
 * @property DetalleActivo $DetalleActivo1
 * @property DetalleActivo $DetalleActivo2
 * 
 * @method integer           getIdDetalleActivo1()   Returns the current record's "id_detalle_activo1" value
 * @method integer           getIdDetalleActivo2()   Returns the current record's "id_detalle_activo2" value
 * @method DetalleActivo     getDetalleActivo1()     Returns the current record's "DetalleActivo1" value
 * @method DetalleActivo     getDetalleActivo2()     Returns the current record's "DetalleActivo2" value
 * @method ReferenciaDetalle setIdDetalleActivo1()   Sets the current record's "id_detalle_activo1" value
 * @method ReferenciaDetalle setIdDetalleActivo2()   Sets the current record's "id_detalle_activo2" value
 * @method ReferenciaDetalle setDetalleActivo1()     Sets the current record's "DetalleActivo1" value
 * @method ReferenciaDetalle setDetalleActivo2()     Sets the current record's "DetalleActivo2" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReferenciaDetalle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('referencia_detalle');
        $this->hasColumn('id_detalle_activo1', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_detalle_activo2', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DetalleActivo as DetalleActivo1', array(
             'local' => 'id_detalle_activo1',
             'foreign' => 'id_detalle_activo'));

        $this->hasOne('DetalleActivo as DetalleActivo2', array(
             'local' => 'id_detalle_activo2',
             'foreign' => 'id_detalle_activo'));
    }
}