<?php

/**
 * BaseReferenciaDocumento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_referencia_documento
 * @property integer $id_factura
 * @property integer $id_guia
 * @property integer $id_boleta
 * @property integer $id_nota_credito
 * @property integer $id_nota_debito
 * @property integer $documento_final
 * @property Factura $Factura
 * @property Guia $Guia
 * @property Boleta $Boleta
 * @property NotaCredito $NotaCredito
 * @property NotaDebito $NotaDebito
 * 
 * @method integer             getIdReferenciaDocumento()   Returns the current record's "id_referencia_documento" value
 * @method integer             getIdFactura()               Returns the current record's "id_factura" value
 * @method integer             getIdGuia()                  Returns the current record's "id_guia" value
 * @method integer             getIdBoleta()                Returns the current record's "id_boleta" value
 * @method integer             getIdNotaCredito()           Returns the current record's "id_nota_credito" value
 * @method integer             getIdNotaDebito()            Returns the current record's "id_nota_debito" value
 * @method integer             getDocumentoFinal()          Returns the current record's "documento_final" value
 * @method Factura             getFactura()                 Returns the current record's "Factura" value
 * @method Guia                getGuia()                    Returns the current record's "Guia" value
 * @method Boleta              getBoleta()                  Returns the current record's "Boleta" value
 * @method NotaCredito         getNotaCredito()             Returns the current record's "NotaCredito" value
 * @method NotaDebito          getNotaDebito()              Returns the current record's "NotaDebito" value
 * @method ReferenciaDocumento setIdReferenciaDocumento()   Sets the current record's "id_referencia_documento" value
 * @method ReferenciaDocumento setIdFactura()               Sets the current record's "id_factura" value
 * @method ReferenciaDocumento setIdGuia()                  Sets the current record's "id_guia" value
 * @method ReferenciaDocumento setIdBoleta()                Sets the current record's "id_boleta" value
 * @method ReferenciaDocumento setIdNotaCredito()           Sets the current record's "id_nota_credito" value
 * @method ReferenciaDocumento setIdNotaDebito()            Sets the current record's "id_nota_debito" value
 * @method ReferenciaDocumento setDocumentoFinal()          Sets the current record's "documento_final" value
 * @method ReferenciaDocumento setFactura()                 Sets the current record's "Factura" value
 * @method ReferenciaDocumento setGuia()                    Sets the current record's "Guia" value
 * @method ReferenciaDocumento setBoleta()                  Sets the current record's "Boleta" value
 * @method ReferenciaDocumento setNotaCredito()             Sets the current record's "NotaCredito" value
 * @method ReferenciaDocumento setNotaDebito()              Sets the current record's "NotaDebito" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReferenciaDocumento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('referencia_documento');
        $this->hasColumn('id_referencia_documento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_factura', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_guia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_boleta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_nota_credito', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_nota_debito', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('documento_final', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'comment' => '1: Factura, 2: Guia, 3: Boleta, 4: NC, 5: ND',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Factura', array(
             'local' => 'id_factura',
             'foreign' => 'id_factura'));

        $this->hasOne('Guia', array(
             'local' => 'id_guia',
             'foreign' => 'id_guia'));

        $this->hasOne('Boleta', array(
             'local' => 'id_boleta',
             'foreign' => 'id_boleta'));

        $this->hasOne('NotaCredito', array(
             'local' => 'id_nota_credito',
             'foreign' => 'id_nota_credito'));

        $this->hasOne('NotaDebito', array(
             'local' => 'id_nota_debito',
             'foreign' => 'id_nota_debito'));
    }
}