<?php
// Connection Component Binding
//Doctrine_Manager::getInstance()->bindComponent('TipoPago', 'artelamp_1');

/**
 * BaseTipoPago
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_tipo_pago
 * @property string $nombre_tipo_pago
 * @property string $descripcion_tipo_pago
 * @property Doctrine_Collection $Pago
 * 
 * @method integer             getIdTipoPago()            Returns the current record's "id_tipo_pago" value
 * @method string              getNombreTipoPago()        Returns the current record's "nombre_tipo_pago" value
 * @method string              getDescripcionTipoPago()   Returns the current record's "descripcion_tipo_pago" value
 * @method Doctrine_Collection getPago()                  Returns the current record's "Pago" collection
 * @method TipoPago            setIdTipoPago()            Sets the current record's "id_tipo_pago" value
 * @method TipoPago            setNombreTipoPago()        Sets the current record's "nombre_tipo_pago" value
 * @method TipoPago            setDescripcionTipoPago()   Sets the current record's "descripcion_tipo_pago" value
 * @method TipoPago            setPago()                  Sets the current record's "Pago" collection
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseTipoPago extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_pago');
        $this->hasColumn('id_tipo_pago', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_tipo_pago', 'string', 50, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('descripcion_tipo_pago', 'string', 512, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 512,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Pago', array(
             'local' => 'id_tipo_pago',
             'foreign' => 'id_tipo_pago'));
    }
}