<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Provincias', 'artelamp');

/**
 * BaseProvincias
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_comunas
 * @property string $descripcion
 * @property integer $relacion
 * 
 * @method integer    getIdComunas()   Returns the current record's "id_comunas" value
 * @method string     getDescripcion() Returns the current record's "descripcion" value
 * @method integer    getRelacion()    Returns the current record's "relacion" value
 * @method Provincias setIdComunas()   Sets the current record's "id_comunas" value
 * @method Provincias setDescripcion() Sets the current record's "descripcion" value
 * @method Provincias setRelacion()    Sets the current record's "relacion" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProvincias extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('provincias');
        $this->hasColumn('id_comunas', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('relacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}