<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CotizacionesProducto', 'artelamp');

/**
 * BaseCotizacionesProducto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_cotizacion
 * @property string $id_producto
 * @property integer $cantidad
 * @property integer $precio
 * @property integer $descuento
 * @property string $nombre
 * @property string $detalle_tecnico
 * @property string $comentario
 * 
 * @method integer              getId()              Returns the current record's "id" value
 * @method integer              getIdCotizacion()    Returns the current record's "id_cotizacion" value
 * @method string               getIdProducto()      Returns the current record's "id_producto" value
 * @method integer              getCantidad()        Returns the current record's "cantidad" value
 * @method integer              getPrecio()          Returns the current record's "precio" value
 * @method integer              getDescuento()       Returns the current record's "descuento" value
 * @method string               getNombre()          Returns the current record's "nombre" value
 * @method string               getDetalleTecnico()  Returns the current record's "detalle_tecnico" value
 * @method string               getComentario()      Returns the current record's "comentario" value
 * @method CotizacionesProducto setId()              Sets the current record's "id" value
 * @method CotizacionesProducto setIdCotizacion()    Sets the current record's "id_cotizacion" value
 * @method CotizacionesProducto setIdProducto()      Sets the current record's "id_producto" value
 * @method CotizacionesProducto setCantidad()        Sets the current record's "cantidad" value
 * @method CotizacionesProducto setPrecio()          Sets the current record's "precio" value
 * @method CotizacionesProducto setDescuento()       Sets the current record's "descuento" value
 * @method CotizacionesProducto setNombre()          Sets the current record's "nombre" value
 * @method CotizacionesProducto setDetalleTecnico()  Sets the current record's "detalle_tecnico" value
 * @method CotizacionesProducto setComentario()      Sets the current record's "comentario" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCotizacionesProducto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cotizaciones_producto');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_cotizacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_producto', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('cantidad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('precio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('descuento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('detalle_tecnico', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('comentario', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}