<?php
// Connection Component Binding
//Doctrine_Manager::getInstance()->bindComponent('EstadoNotaCredito', 'artelamp_1');

/**
 * BaseEstadoNotaCredito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_estado_nota_credito
 * @property string $nombre_estado_nota_credito
 * @property string $descripcion_estado_nota_credito
 * @property Doctrine_Collection $NotaCredito
 * 
 * @method integer             getIdEstadoNotaCredito()             Returns the current record's "id_estado_nota_credito" value
 * @method string              getNombreEstadoNotaCredito()         Returns the current record's "nombre_estado_nota_credito" value
 * @method string              getDescripcionEstadoNotaCredito()    Returns the current record's "descripcion_estado_nota_credito" value
 * @method Doctrine_Collection getNotaCredito()                     Returns the current record's "NotaCredito" collection
 * @method EstadoNotaCredito   setIdEstadoNotaCredito()             Sets the current record's "id_estado_nota_credito" value
 * @method EstadoNotaCredito   setNombreEstadoNotaCredito()         Sets the current record's "nombre_estado_nota_credito" value
 * @method EstadoNotaCredito   setDescripcionEstadoNotaCredito()    Sets the current record's "descripcion_estado_nota_credito" value
 * @method EstadoNotaCredito   setNotaCredito()                     Sets the current record's "NotaCredito" collection
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseEstadoNotaCredito extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado_nota_credito');
        $this->hasColumn('id_estado_nota_credito', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_estado_nota_credito', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('descripcion_estado_nota_credito', 'string', 512, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 512,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('NotaCredito', array(
             'local' => 'id_estado_nota_credito',
             'foreign' => 'id_estado_nota_credito'));
    }
}