<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Existencia', 'artelamp');

/**
 * BaseExistencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_existencia
 * @property integer $id_espacio
 * @property string $codigo_existencia
 * @property integer $cantidad_existencia
 * @property string $comentario_existencia
 * @property timestamp $fecha_existencia
 * @property Espacio $Espacio
 * 
 * @method integer    getIdExistencia()          Returns the current record's "id_existencia" value
 * @method integer    getIdEspacio()             Returns the current record's "id_espacio" value
 * @method string     getCodigoExistencia()      Returns the current record's "codigo_existencia" value
 * @method integer    getCantidadExistencia()    Returns the current record's "cantidad_existencia" value
 * @method string     getComentarioExistencia()  Returns the current record's "comentario_existencia" value
 * @method timestamp  getFechaExistencia()       Returns the current record's "fecha_existencia" value
 * @method Espacio    getEspacio()               Returns the current record's "Espacio" value
 * @method Existencia setIdExistencia()          Sets the current record's "id_existencia" value
 * @method Existencia setIdEspacio()             Sets the current record's "id_espacio" value
 * @method Existencia setCodigoExistencia()      Sets the current record's "codigo_existencia" value
 * @method Existencia setCantidadExistencia()    Sets the current record's "cantidad_existencia" value
 * @method Existencia setComentarioExistencia()  Sets the current record's "comentario_existencia" value
 * @method Existencia setFechaExistencia()       Sets the current record's "fecha_existencia" value
 * @method Existencia setEspacio()               Sets the current record's "Espacio" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExistencia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('existencia');
        $this->hasColumn('id_existencia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_espacio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo_existencia', 'string', 15, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('cantidad_existencia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('comentario_existencia', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('fecha_existencia', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Espacio', array(
             'local' => 'id_espacio',
             'foreign' => 'id_espacio'));
    }
}