<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Regiones', 'artelamp');

/**
 * BaseRegiones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_regiones
 * @property string $descripcion
 * @property string $relacion
 * 
 * @method integer  getIdRegiones()  Returns the current record's "id_regiones" value
 * @method string   getDescripcion() Returns the current record's "descripcion" value
 * @method string   getRelacion()    Returns the current record's "relacion" value
 * @method Regiones setIdRegiones()  Sets the current record's "id_regiones" value
 * @method Regiones setDescripcion() Sets the current record's "descripcion" value
 * @method Regiones setRelacion()    Sets the current record's "relacion" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegiones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('regiones');
        $this->hasColumn('id_regiones', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('relacion', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}