<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EstadoComponente', 'artelamp');

/**
 * BaseEstadoComponente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_estado
 * @property string $nombre_estado
 * @property string $descripcion_estado
 * 
 * @method integer          getIdEstado()           Returns the current record's "id_estado" value
 * @method string           getNombreEstado()       Returns the current record's "nombre_estado" value
 * @method string           getDescripcionEstado()  Returns the current record's "descripcion_estado" value
 * @method EstadoComponente setIdEstado()           Sets the current record's "id_estado" value
 * @method EstadoComponente setNombreEstado()       Sets the current record's "nombre_estado" value
 * @method EstadoComponente setDescripcionEstado()  Sets the current record's "descripcion_estado" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseEstadoComponente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado_componente');
        $this->hasColumn('id_estado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_estado', 'string', 2000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2000,
             ));
        $this->hasColumn('descripcion_estado', 'string', 2000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}