<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ParametroFactura', 'artelamp');

/**
 * BaseParametroFactura
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $campo
 * @property integer $x
 * @property integer $y
 * @property integer $tam_letra
 * 
 * @method integer          getId()        Returns the current record's "id" value
 * @method string           getCampo()     Returns the current record's "campo" value
 * @method integer          getX()         Returns the current record's "x" value
 * @method integer          getY()         Returns the current record's "y" value
 * @method integer          getTamLetra()  Returns the current record's "tam_letra" value
 * @method ParametroFactura setId()        Sets the current record's "id" value
 * @method ParametroFactura setCampo()     Sets the current record's "campo" value
 * @method ParametroFactura setX()         Sets the current record's "x" value
 * @method ParametroFactura setY()         Sets the current record's "y" value
 * @method ParametroFactura setTamLetra()  Sets the current record's "tam_letra" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParametroFactura extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parametro_factura');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('campo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('x', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('y', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tam_letra', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}