<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Log', 'artelamp');

/**
 * BaseLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_usuario
 * @property integer $id_salida
 * @property timestamp $fecha
 * @property string $campo_mod
 * @property string $valor_antiguo
 * @property string $valor_nuevo
 * 
 * @method integer   getIdUsuario()     Returns the current record's "id_usuario" value
 * @method integer   getIdSalida()      Returns the current record's "id_salida" value
 * @method timestamp getFecha()         Returns the current record's "fecha" value
 * @method string    getCampoMod()      Returns the current record's "campo_mod" value
 * @method string    getValorAntiguo()  Returns the current record's "valor_antiguo" value
 * @method string    getValorNuevo()    Returns the current record's "valor_nuevo" value
 * @method Log       setIdUsuario()     Sets the current record's "id_usuario" value
 * @method Log       setIdSalida()      Sets the current record's "id_salida" value
 * @method Log       setFecha()         Sets the current record's "fecha" value
 * @method Log       setCampoMod()      Sets the current record's "campo_mod" value
 * @method Log       setValorAntiguo()  Sets the current record's "valor_antiguo" value
 * @method Log       setValorNuevo()    Sets the current record's "valor_nuevo" value
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('log');
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_salida', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('campo_mod', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('valor_antiguo', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('valor_nuevo', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}