<?php

/**
 * ActivosCompuestosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivosCompuestosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivosCompuestosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivosCompuestos');
    }
}