<?php

/**
 * ActivosSimplesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivosSimplesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivosSimplesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivosSimples');
    }
}