<?php

/**
 * BoletaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BoletaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BoletaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Boleta');
    }
}