<?php

/**
 * Boleta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Boleta extends BaseBoleta
{
    public function getNetoCalculado(){
        $neto = 0;
        foreach ($this->getDetalleActivo() as $detalle){
            $neto += $detalle->getPrecioDetalleActivo()*$detalle->getCantidadDetalleActivo();
        }
        return $neto;
    }

}