<?php

/**
 * ClienteHistorialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClienteHistorialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClienteHistorialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClienteHistorial');
    }
}