<?php

/**
 * CompuestoSimpleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompuestoSimpleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompuestoSimpleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompuestoSimple');
    }
}