<?php

/**
 * CostosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CostosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CostosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Costos');
    }
}