<?php

/**
 * CotizacionesEstadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CotizacionesEstadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CotizacionesEstadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CotizacionesEstado');
    }
}