<?php

/**
 * CotizacionesProductoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CotizacionesProductoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CotizacionesProductoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CotizacionesProducto');
    }
}