<?php

/**
 * Cuota
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Cuota extends BaseCuota
{
    public function estaVencido() {
        list($dia,$mes,$año)=split("/", $this->getDateTimeObject('fechavencimiento_cuota')->format('d/m/Y'));
        $fechacuota = mktime(0,0,0, $mes,$dia,$año);
        $fechahoy = mktime(0, 0, 0);
        if ($fechacuota >= $fechahoy) {
            if($this->getMontoCuota() == $this->getMontopagadoCuota()) $this->setEstado('Pagada');
            else $this->setEstado('Por Pagar');
            return false;
        } else {
            $this->setEstado('Vencida');
            return true;
        }
        
    }

    public function ValidarEstado(){
        if($this->getMontoCuota() == $this->getMontopagadoCuota()) $this->setEstado('Pagada');
        else if($this->estaVencido()){
            $this->setEstado('Vencida');
        }
        else $this->setEstado('Por Pagar');
    }


    public function setEstado($estado){
        $EC = Doctrine::getTable('EstadoCuota')->findOneByNombreEstadoCuota($estado);
        if($EC == NULL) throw new Exception('Cuota envalida');
        if($EC != NULL && $this->getEstadoCuota()->getNombreEstadoCuota() != $estado){
            $this->setEstadoCuota($EC);
            $this->save();
        }
    }


    public function ValidarSaldoFactura(){
        $this->getFactura()->ValidarSaldo();
    }

    public function getComentarioCuotaTD(){
        if($this->getComentarioCuota() != ''){
            $td = '<td title="'.$this->getComentarioCuota().'" align="center"><img alt="comentario" width="20px" src="/images1/comentario.jpg" /></td>';
        }
        else{
            $td = '<td></td>';
        }
        return $td;
    }

    public function __toString() {
        return sprintf('%s Cuota de %s en NF%s', $this->getIdCuota(), $this->getFactura()->getNombreFactura(), $this->getFactura()->getNumeroFactura());
    }

}