<?php

/**
 * DespachoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DespachoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DespachoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Despacho');
    }
}