<?php

/**
 * DetalleActivoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleActivoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleActivoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleActivo');
    }
}