<?php

/**
 * DetalleReposicionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleReposicionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleReposicionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleReposicion');
    }
}