<?php

/**
 * DivisionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DivisionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DivisionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Divisiones');
    }
}