<?php

/**
 * EspacioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EspacioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EspacioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Espacio');
    }
}