<?php

/**
 * EstadoCuotaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoCuotaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadoCuotaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadoCuota');
    }
}