<?php

/**
 * EstadoNotaCreditoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoNotaCreditoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadoNotaCreditoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadoNotaCredito');
    }
}