<?php

/**
 * EstadoGuiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoGuiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadoGuiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadoGuia');
    }
}