<?php

/**
 * EstadoBoletaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoBoletaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadoBoletaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadoBoleta');
    }
}