<?php

/**
 * EstadoNotaDebitoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoNotaDebitoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadoNotaDebitoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadoNotaDebito');
    }
}