<?php

/**
 * ExistenciaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExistenciaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExistenciaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Existencia');
    }
}