<?php

/**
 * FacturaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FacturaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FacturaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Factura');
    }

    static public $types = array(
    'FISICA' => 'FISICA',
    'ELECTRONICA' => 'ELECTRONICA',
    );

    public function getTipos()
    {
        return self::$types;
    }
}