<?php

/**
 * FormasPagoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormasPagoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormasPagoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormasPago');
    }
}