<?php

/**
 * HistCuotaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HistCuotaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HistCuotaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HistCuota');
    }
}