<?php

/**
 * HistPagoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HistPagoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HistPagoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HistPago');
    }
}