<?php

/**
 * InfoContactosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InfoContactosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InfoContactosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InfoContactos');
    }
}