<?php

/**
 * NivelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NivelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NivelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Nivel');
    }
}