<?php

/**
 * NotacreditoDetalleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotacreditoDetalleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotacreditoDetalleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotacreditoDetalle');
    }
}