<?php

/**
 * NotaCredito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class NotaCredito extends BaseNotaCredito
{    
    public function getNetoCalculado(){
        $neto = 0;
        foreach ($this->getDetalleActivo() as $nc){
            $neto += $nc->getPrecioDetalleActivo()*$nc->getCantidadDetalleActivo();
        }
        return $neto;
    }

    public function save(Doctrine_Connection $conn = null) {
        if ($this->isNew()){
            //SE INGRESA CON LA FECHA ACTUAL
            $this->setFechaingresoNotaCredito(date('Y-m-d H:i:s'));
            //ESTADO EMITIDA
            $EEMITIDA = Doctrine::getTable('EstadoNotaCredito')->findOneByNombreEstadoNotaCredito('Emitida');            
            $this->setEstadoNotaCredito($EEMITIDA);
            $this->setTipoNotaCredito('FISICA');
        }
        if($this->getGlosaNotaDebito() == '') $this->setGlosaNotaDebito (null);

        return parent::save($conn);
    }
}