<?php

/**
 * NotaDebitoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotaDebitoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotaDebitoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotaDebito');
    }
}