<?php

/**
 * NotadebitoDetalleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotadebitoDetalleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotadebitoDetalleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotadebitoDetalle');
    }
}