<?php

/**
 * NotaCreditoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotaCreditoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotaCreditoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotaCredito');
    }
}