<?php

/**
 * NotaDebitoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotaDebitoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotaDebitoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotaDebito');
    }
    
    
    static public $CodRef = array(
    '1' => 'Anula Doc de Referencia',
    '2' => 'Corrige Texto Doc de Ref',
    '3' => 'Corrige Montos',
    );
    static public $TipoDoc = array(
    '33' => '[33]FACTURA ELEC.',
    '39' => '[39]BOLETA ELEC.',
    '56' => '[56]NOTA DEBITO ELEC.',
    );
 
      public function getCodRefs()
      {
        return self::$CodRef;
      }
      public function getTipoDoc()
      {
        return self::$TipoDoc;
      }
}