<?php

/**
 * Pago
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Pago extends BasePago
{
    public function save(Doctrine_Connection $conn = null)
  {
    if ($this->isNew())
    {
      $now = time();
//      $this->setExpiresAt(date('Y-m-d H:i:s', $now + 86400 * 30));
      $this->setFechaPago(date('Y-m-d H:i:s', $now));
    }

    return parent::save($conn);
  }
}