<?php

/**
 * ParametroGuiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParametroGuiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParametroGuiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ParametroGuia');
    }
}