<?php

/**
 * ParametroFacturaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParametroFacturaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParametroFacturaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ParametroFactura');
    }
}