<?php

/**
 * PasilloTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PasilloTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PasilloTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pasillo');
    }
}