<?php

/**
 * ReferenciaDocumentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReferenciaDocumentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReferenciaDocumentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReferenciaDocumento');
    }
}