<?php

/**
 * SalidaActivoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SalidaActivoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SalidaActivoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SalidaActivo');
    }
}