<?php

/**
 * SalidaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SalidaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SalidaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Salida');
    }
}