<?php

/**
 * TipoPago
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sffacturacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class TipoPago extends BaseTipoPago
{
    public function __toString() {
        return sprintf('%s', $this->getNombreTipoPago());
    }

}