<?php

/**
 * TransaccionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TransaccionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TransaccionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Transacciones');
    }
}