<?php

/**
 * UsuariosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuariosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuariosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Usuarios');
    }
    
    public function getUsuariosParaChoice()
    {
        $users = Doctrine_Core::getTable('Usuarios')
                ->createQuery('a')
                ->select('a.descripcion')
                ->where('vendedor = ?', '1')
                ->execute();
        $resultado = array();
        foreach ($users as $user){
            $resultado[strtoupper($user->getDescripcion())] = strtoupper($user->getDescripcion());
        }
        return $resultado;
    }
}