# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

all:
  artelamp_1:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=artelamp_1'
      username: root
      password: null
      persistent: true
#  artelamp_2:
#    class: sfDoctrineDatabase
#    param:
#      dsn: 'mysql:host=localhost;dbname=artelamp_2'
#      username: root
#      password: null
#      persistent: true
  artelamp:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=artelamp'
      username: root
      password: null
      persistent: true
